# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Gatsby Publish

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ] ## to delet after checking success

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: enriikke/gatsby-gh-pages-action@v2
      with:
        access-token: ${{ secrets.GITHUB_TOKEN }}
        # The branch expected by GitHub to have the static files needed for your site.
        deploy-branch: gh-pages
        gatsby-args: --prefix-paths
